spring.application.name=orchestrator

server.port=8080

# spring.activemq.broker-url=tcp://localhost::61616


# Nombre de las colas donde enviaremos mensajes
app.jms.queueCreateUser=queueCreateUser
app.jms.queueCreateTypeUser=queueCreateTypeUser
app.jms.queueOrchestratorEvents=queueOrchestratorEvents